---
# {{ cookiecutter.role_name }} molecule/default/verify.yml
#
# SPDX-FileCopyrightText: {{ cookiecutter.year }} {{ cookiecutter.author }} <{{ cookiecutter.email }}>
# SPDX-License-Identifier: {{ cookiecutter.license }}

- name: Verify
  hosts: all
  tasks:
  - name: example assertion
    assert:
      that: true
